# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='channels.Channel'),
        ),
    ]
